<a href="https://colab.research.google.com/github/carlosjuliogarciaorjuela/machine-learning-educative-1/blob/main/curso_machine_learning_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Matrices Numpy**

In [2]:
# crear una matriz 2D:

import numpy as np

arr = np.array([[0, 1, 2], [3, 4, 5]],
               dtype=np.float32)

print(repr(arr))




array([[0., 1., 2.],
       [3., 4., 5.]], dtype=float32)


In [3]:
# np.array upcasting, Ambos números enteros se convierten a sus equivalentes de
# punto flotante.

arr = np.array([0, 0.1, 2])
print(repr(arr))


array([0. , 0.1, 2. ])


**¿Son los arrays de NumPy más rápidos que los arrays de Python?**

Los arrays de NumPy son más rápidos que las listas de Python porque almacenan los elementos en memoria contigua y admiten operaciones vectorizadas, lo que reduce la sobrecarga y acelera los cálculos numéricos.



# **B. Copia de matrices NumPy (superficial vs. profunda)**

In [4]:
a = np.array([0, 1])
b = np.array([9, 8])
c = a
print('Array a: {}'.format(repr(a)))
c[0] = 5
print('Array a: {}'.format(repr(a)))

d = b.copy()
d[0] = 6
print('Array b: {}'.format(repr(b)))


Array a: array([0, 1])
Array a: array([5, 1])
Array b: array([9, 8])


# **C. Conversión de matrices NumPy**

In [5]:
# Conversion de tipos mediante la astype function,
# dtype property, devuelve el tipo de un array.

arr = np.array([0, 1, 2])
print(arr.dtype)
arr = arr.astype(np.float32)
print(arr.dtype)

int64
float32


# **D. Manejo de valores faltantes con np.nan**


In [6]:
# uso de np.nan, no puede aceptar un tipo entero-
arr = np.array([np.nan, 1, 1])
print(repr(arr))

arr = np.array([np.nan, 'abc'])
print(repr(arr))

np.array([np.nan, 1, 2], dtype=np.float32)


array([nan,  1.,  1.])
array(['nan', 'abc'], dtype='<U32')


array([nan,  1.,  2.], dtype=float32)

# **E. Using np.inf in NumPy**


In [7]:
print(np.inf > 1000000)

arr = np.array([np.inf, 5])
print(repr(arr))

arr = np.array([-np.inf, 1])
print(repr(arr))

# Will result in a OverflowError: If we uncomment line 10 and run again.
#np.array([np.inf, 3], dtype=np.int32)
np.array([np.inf, 3], dtype=np.float32)

True
array([inf,  5.])
array([-inf,   1.])


array([inf,  3.], dtype=float32)

# **Conceptos básicos de NumPy**

In [8]:
# A. Ranged data
arr = np.arange(5)
print(repr(arr))

arr = np.arange(5.1)
print(repr(arr))

arr = np.arange(-1, 4)
print(repr(arr))

arr = np.arange(-1.5, 4, 2)
print(repr(arr))

arr = np.arange(0,1,0.1)
print(repr(arr.astype(np.int32)))

array([0, 1, 2, 3, 4])
array([0., 1., 2., 3., 4., 5.])
array([-1,  0,  1,  2,  3])
array([-1.5,  0.5,  2.5])
array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)


# **linspace**

Para especificar el número de elementros en el array devuelto, en lugar del tamaño del paso.

Esta función requiere dos argumentos para el inicio y el final del rango.*italicized text*

In [9]:

arr = np.linspace(5, 11, num=4)
print(repr(arr))

arr = np.linspace(5, 11, num=4, endpoint=False)
print(repr(arr))

arr = np.linspace(5, 11, num=4, dtype=np.int32)
print(repr(arr))


array([ 5.,  7.,  9., 11.])
array([5. , 6.5, 8. , 9.5])
array([ 5,  7,  9, 11], dtype=int32)


# **Reshaping data**
La función que usamos para redimensionar datos en NumPy es np.reshape. Recibe como argumentos obligatorios un array y una nueva forma. La nueva forma debe contener exactamente todos los elementos del array de entrada. Por ejemplo, podríamos redimensionar un array con 12 elementos a (4, 3), pero no podemos redimensionarlo a (4, 4).

Se nos permite usar el valor especial de -1 en, como máximo, una dimensión de la nueva figura. La dimensión con -1 adoptará el valor necesario para que la nueva figura contenga todos los elementos del arreglo.

El código que aparece a continuación muestra ejemplos de uso de np.reshape.

In [10]:
arr = np.arange(8)

reshaped_arr = np.reshape(arr, (2, 4))
print(repr(reshaped_arr))
print('New shape: {}'.format(reshaped_arr.shape))

reshaped_arr = np.reshape(arr, (-1, 2, 2))
print(repr(reshaped_arr))
print('New shape: {}'.format(reshaped_arr.shape))



array([[0, 1, 2, 3],
       [4, 5, 6, 7]])
New shape: (2, 4)
array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])
New shape: (2, 2, 2)


NumPy proporciona una función integrada para aplanar un array. Aplanar un array lo transforma en un array unidimensional. Dado que a menudo necesitamos aplanar datos, esta función resulta muy útil.
El siguiente código aplana un array utilizando la flattenfunción integrada.

In [11]:
arr = np.arange(8)

arr = np.reshape(arr, (2, 4))
flattened = arr.flatten()

print(repr(arr))
print('arr shape: {}'.format(arr.shape))
print(repr(flattened))
print('flattened shape: {}'.format(flattened.shape))


array([[0, 1, 2, 3],
       [4, 5, 6, 7]])
arr shape: (2, 4)
array([0, 1, 2, 3, 4, 5, 6, 7])
flattened shape: (8,)


# **Transposing**

Se puede reformatear datos, también se puede transponerlos.

Quizás tengamos datos que deberían estar en un formato específico, pero algunos datos nuevos que recibimos están reorganizados. Podemos simplemente transponer los datos, utilizando la np.transposefunción correspondiente, para convertirlos al formato correcto

El siguiente código muestra un ejemplo de uso de la np.transposefunción. Tras la transposición, las filas de la matriz se convierten en columnas.


In [12]:
arr = np.arange(8)
arr = np.reshape(arr, (4, 2))
transposed = np.transpose(arr)

print(repr(arr))
print('arr shape: {}'.format(arr.shape))
print(repr(transposed))
print('transposed shape: {}'.format(transposed.shape))


array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])
arr shape: (4, 2)
array([[0, 2, 4, 6],
       [1, 3, 5, 7]])
transposed shape: (2, 4)


# **Zeros and ones**

A veces, necesitamos crear matrices que contengan únicamente 0 o 1. Por ejemplo, dado que los datos binarios se etiquetan con 0 y 1, podríamos necesitar crear conjuntos de datos ficticios con una sola etiqueta. Para crear estas matrices, NumPy proporciona las funciones np.zerosy np.ones. Ambas aceptan los mismos argumentos, que incluyen un único argumento obligatorio: la forma de la matriz. Las funciones también permiten la conversión manual de tipos mediante el dtypeargumento de palabra clave.

El código que aparece a continuación muestra ejemplos de uso de np.zerosy np.ones.

In [13]:
arr = np.zeros(4)
print(repr(arr))

arr = np.ones((2, 3))
print(repr(arr))

arr = np.ones((2, 3), dtype=np.int32)
print(repr(arr))

array([0., 0., 0., 0.])
array([[1., 1., 1.],
       [1., 1., 1.]])
array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)


Si queremos crear una matriz de 0 o 1 con la misma forma que otra matriz, podemos usar np.zeros_likey np.ones_like.

El código que aparece a continuación muestra ejemplos de uso de np.zeros_likey np.ones_like.

In [14]:
arr = np.array([[1, 2], [3, 4]])
print(repr(np.zeros_like(arr)))

arr = np.array([[0., 1.], [1.2, 4]])
print(repr(np.ones_like(arr)))
print(repr(np.ones_like(arr, dtype=np.int32)))

array([[0, 0],
       [0, 0]])
array([[1., 1.],
       [1., 1.]])
array([[1, 1],
       [1, 1]], dtype=int32)


Time to Code!
Our initial array will just be all the integers from 0 to 11, inclusive. We'll also reshape it so it has three dimensions.

First, set arr equal to np.arange with 12 as the only argument.

Then, set reshaped equal to np.reshape with arr as the first argument and (2, 3, 2) as the second argument.

In [15]:
arr = np.arange(12)
print(repr(arr))

reshaped = np.reshape(arr, (2, 3, 2))
print(repr(reshaped))
print('New shape: {}'.format(reshaped.shape))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])
New shape: (2, 3, 2)


Next we want to get a flattened version of the reshaped array (the flattened version is equivalent to arr, as well as a transposed version. For the transposed version of reshaped, we use a permutation of 1, 2, 0).
Set flattened equal to reshaped.flatten().
Then set transposed equal to np.transpose with reshaped as the first argument and the specified permutation for the axes keyword argument.

In [16]:
arr = np.arange(12)

reshaped = np.reshape(arr, (2, 3, 2))

# Aplanar el arreglo redimensionado
flattened = reshaped.flatten()
print(repr(flattened))
print('arr shape: {}'.format(arr.shape))
print(repr(flattened))
print('flattened shape: {}'.format(flattened.shape))

# Transponer 'reshaped' usando la permutación (1, 2, 0)
transposed = np.transpose(reshaped, axes=(1, 2, 0))
print('arr shape: {}'.format(reshaped.shape))
print('transposed shape: {}'.format(transposed.shape))



array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
arr shape: (12,)
array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
flattened shape: (12,)
arr shape: (2, 3, 2)
transposed shape: (3, 2, 2)


We'll create an array of 5 elements, all of which are 0. We'll also create an array with the same shape as transposed, but containing only 1 as the elements.

Set zeros_arr equal to np.zeros with 5 as the lone argument.

Then set ones_arr equal to np.ones_like with transposed as the lone argument.

In [17]:
zeros_arr = np.zeros(5)
print(repr(zeros_arr))

ones_arr = np.ones_like(transposed)
print(repr(ones_arr))

array([0., 0., 0., 0., 0.])
array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])


The final array will contain 101 evenly spaced numbers between -3.5 and 1.5, inclusive. Since they are evenly spaced, the difference between adjacent numbers is 0.05.

Set points equal to np.linspace with -3.5 and 1.5 as the first two arguments, respectively, as well as 101 for the num keyword argument.

In [18]:
points = np.linspace(-3.5, 1.5, num=101)
print(repr(points))

array([-3.5 , -3.45, -3.4 , -3.35, -3.3 , -3.25, -3.2 , -3.15, -3.1 ,
       -3.05, -3.  , -2.95, -2.9 , -2.85, -2.8 , -2.75, -2.7 , -2.65,
       -2.6 , -2.55, -2.5 , -2.45, -2.4 , -2.35, -2.3 , -2.25, -2.2 ,
       -2.15, -2.1 , -2.05, -2.  , -1.95, -1.9 , -1.85, -1.8 , -1.75,
       -1.7 , -1.65, -1.6 , -1.55, -1.5 , -1.45, -1.4 , -1.35, -1.3 ,
       -1.25, -1.2 , -1.15, -1.1 , -1.05, -1.  , -0.95, -0.9 , -0.85,
       -0.8 , -0.75, -0.7 , -0.65, -0.6 , -0.55, -0.5 , -0.45, -0.4 ,
       -0.35, -0.3 , -0.25, -0.2 , -0.15, -0.1 , -0.05,  0.  ,  0.05,
        0.1 ,  0.15,  0.2 ,  0.25,  0.3 ,  0.35,  0.4 ,  0.45,  0.5 ,
        0.55,  0.6 ,  0.65,  0.7 ,  0.75,  0.8 ,  0.85,  0.9 ,  0.95,
        1.  ,  1.05,  1.1 ,  1.15,  1.2 ,  1.25,  1.3 ,  1.35,  1.4 ,
        1.45,  1.5 ])


# **Math **

Explore how to execute essential math operations with NumPy, including arithmetic on multi-dimensional arrays, non-linear functions like exponentials and logarithms, and matrix multiplication. Learn to leverage these tools for effective data manipulation in machine learning applications.

Chapter Goals:
Learn how to perform math operations in NumPy
Write code using NumPy math functions
A. Arithmetic
One of the main purposes of NumPy is to perform multi-dimensional arithmetic. Using NumPy arrays, we can apply arithmetic to each element with a single operation.

The code below shows multi-dimensional arithmetic with NumPy.

In [19]:
arr = np.array([[1, 2], [3, 4]])

In [20]:
print(repr(arr))

array([[1, 2],
       [3, 4]])


In [21]:
print(repr(arr + 1))

array([[2, 3],
       [4, 5]])


In [22]:
print(repr(arr - 1.2))

array([[-0.2,  0.8],
       [ 1.8,  2.8]])


In [23]:
print(repr(arr * 2))

array([[2, 4],
       [6, 8]])


In [24]:
print(repr(arr / 2))

array([[0.5, 1. ],
       [1.5, 2. ]])


In [25]:
print(repr(arr // 2))

array([[0, 1],
       [1, 2]])


In [26]:
print(repr(arr**2))

array([[ 1,  4],
       [ 9, 16]])


In [27]:
print(repr(arr**0.5))

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])


In [28]:
# funcion para convertir grados Fahrenheit a grados Celcius
def f2c(temps):
  return (5/9)*(temps-32)

fahrenheits = np.array([32, -4, 14, -40])
celsius = f2c(fahrenheits)
print('Celsius: {}'.format(repr(celsius)))

Celsius: array([  0., -20., -10., -40.])


# **Non-linear functions**
**FUNCIONES NO LINEALES**
Además de las operaciones aritméticas básicas,

NumPy también permite utilizar funciones no lineales como exponenciales y logaritmos.

La función np.exp una exponencial en base enp.exp2 sobre un arreglo,

mientras que la función realiza una exponencial en base 2.

Del mismo modo, np.log, np.log2, y np.log10 realizan logaritmos sobre un arreglo de entrada, utilizando base e , base 2 y base 10, respectivamente.

El código que se muestra a continuación ilustra diversas exponenciales y logaritmos con NumPy. Nótese que np.ey np.pirepresentan las constantes matemáticas e y π, respectivamente.

In [29]:
arr = np.array([[1, 2], [3, 4]])
# Raised to power of e
print(repr(np.exp(arr)))
# Raised to power of 2
print(repr(np.exp2(arr)))

arr2 = np.array([[1, 10], [np.e, np.pi]])
# Natural logarithm
print(repr(np.log(arr2)))
# Base 10 logarithm
print(repr(np.log10(arr2)))

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])
array([[ 2.,  4.],
       [ 8., 16.]])
array([[0.        , 2.30258509],
       [1.        , 1.14472989]])
array([[0.        , 1.        ],
       [0.43429448, 0.49714987]])


Para realizar una operación de potenciación con cualquier base, utilizamos la función np.power. El primer argumento de la función es la base, mientras que el segundo es la potencia. Si la base o la potencia es un array en lugar de un solo número, la operación se aplica a cada elemento del array.

El siguiente código muestra ejemplos de uso de np.power.

In [30]:
arr = np.array([[1, 2], [3, 4]])
# Raise 3 to power of each number in arr
print(repr(np.power(3, arr)))
arr2 = np.array([[10.2, 4], [3, 5]])
# Raise arr2 to power of each number in arr
print(repr(np.power(arr2, arr)))

array([[ 3,  9],
       [27, 81]])
array([[ 10.2,  16. ],
       [ 27. , 625. ]])



Multiplicación de matrices

Dado que los arreglos de NumPy son básicamente vectores y matrices, es lógico que existan funciones para el producto escalar y la multiplicación de matrices.

En concreto, la función principal que se utiliza es np.matmul, que toma como entrada dos arreglos de vectores/matrices y produce un producto escalar o una multiplicación de matrices.

El código que se muestra a continuación presenta varios ejemplos de multiplicación de matrices. Cuando ambas entradas son unidimensionales, la salida es el producto escalar.

Tenga en cuenta que las dimensiones de las dos matrices de entrada deben ser válidas para una multiplicación de matrices. Específicamente, la segunda dimensión de la primera matriz debe ser igual a la primera dimensión de la segunda matriz; de lo contrario, np.matmulse producirá un error ValueError.

In [31]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([-3, 0, 10])
print(np.matmul(arr1, arr2))

arr3 = np.array([[1, 2], [3, 4], [5, 6]])
arr4 = np.array([[-1, 0, 1], [3, 2, -4]])
print(repr(np.matmul(arr3, arr4)))
print(repr(np.matmul(arr4, arr3)))
# This will result in a ValueError: If we uncomment line 10 and run again.
#print(repr(np.matmul(arr3, arr3)))

27
array([[  5,   4,  -7],
       [  9,   8, -13],
       [ 13,  12, -19]])
array([[  4,   4],
       [-11, -10]])


Random

Explore how to apply random operations in NumPy including generating random integers, sampling from uniform and normal distributions, custom probability sampling, and in-place shuffling of arrays. This lesson helps you understand and write code using the np.random submodule to manipulate data effectively for machine learning tasks.

Chapter Goals:

Learn about random operations in NumPy
Write code using the np.random submodule
A. Random integers
Similar to the Python random module, NumPy has its own submodule for pseudo-random number generation called np.random. It provides all the necessary randomized operations and extends it to multi-dimensional arrays. To generate pseudo-random integers, we use the np.random.randint function.

The code below shows example usages of np.random.randint.

In [33]:
print(np.random.randint(5))
print(np.random.randint(5))
print(np.random.randint(5, high=6))

random_arr = np.random.randint(-3, high=14, size=(2, 2))
print(repr(random_arr))

3
3
5
array([[-3, -3],
       [ 7,  0]])


# **Utility Functions**

Some fundamental utility functions from the np.random module are np.random.seed and np.random.shuffle. We use the np.random.seed function to set the random seed, which allows us to control the outputs of the pseudo-random functions. The function takes in a single integer as an argument, representing the random seed.

The code below uses np.random.seed with the same random seed. Note how the outputs of the random functions in each subsequent run are identical when we set the same random seed.

In [38]:
np.random.seed(1)
print(np.random.randint(10))
random_arr = np.random.randint(3, high=100, size=(2, 2))
print(repr(random_arr))

# new seed
np.random.seed(2)
print(np.random.randint(10))
random_arr = np.random.randint(3, high=100, size=(2, 2))

print(repr(random_arr))

# Original seed
np.random.seed(1)
print(np.random.randint(10))
random_arr = np.random.randint(3, high=100, size=(2, 2))

print(repr(random_arr))

5
array([[15, 75],
       [12, 78]])
8
array([[18, 75],
       [25, 46]])
5
array([[15, 75],
       [12, 78]])


The np.random.shuffle function allows us to randomly shuffle an array. Note that the shuffling happens in place (i.e. no return value), and shuffling multi-dimensional arrays only shuffles the first dimension.

The code below shows example usages of np.random.shuffle. Note that only the rows of matrix are shuffled (i.e. shuffling along first dimension only).

In [43]:
vec = np.array([1, 2, 3, 4, 5])
np.random.shuffle(vec)
print(repr(vec))
np.random.shuffle(vec)
print(repr(vec))

matrix = np.array([[1, 2, 3],
 [4, 5, 6],
  [7, 8, 9]])
np.random.shuffle(matrix)
print(repr(matrix))

array([3, 1, 5, 4, 2])
array([4, 5, 3, 2, 1])
array([[7, 8, 9],
       [1, 2, 3],
       [4, 5, 6]])


Distributions

Using np.random we can also draw samples from probability distributions. For example, we can use np.random.uniform to draw pseudo-random real numbers from a uniform distribution.

The code below shows usages of np.random.uniform.

In [44]:
print(np.random.uniform())
print(np.random.uniform(low=-1.5, high=2.2))
print(np.random.uniform(size=3))
print(repr(np.random.uniform(low=-3.4, high=5.9, size=(2, 2))))

0.8296033593941836
-0.4897150953980347
[0.0592432  0.67052804 0.59306552]
array([[ 2.84638311,  0.42962727],
       [-1.56277665, -0.70644434]])


The function np.random.uniform actually has no required arguments.

The keyword arguments, low and high, represent the inclusive lower end and exclusive upper end from which to draw random samples.

Since they have default values of 0.0 and 1.0, respectively, the default outputs of np.random.uniform come from the range [0.0, 1.0).

The size keyword argument is the same as the one for np.random.randint, i.e. it represents the output size of the array.

Another popular distribution we can sample from is the normal (Gaussian) distribution. The function we use is np.random.normal.

The code below shows usages of np.random.normal.

In [46]:
print(np.random.normal())
print(np.random.normal(loc=1.5, scale=3.5))
print(repr(np.random.normal(loc=-2.4, scale=4.0, size=(2, 2))))

-0.45452082414500417
1.201316780645874
array([[ 3.61275352,  2.24256449],
       [-4.33176559, -9.62651604]])


Like np.random.uniform, np.random.normal has no required arguments.

The loc and scale keyword arguments represent the mean and standard deviation, respectively, of the normal distribution we sample from.

NumPy provides quite a few more built-in distributions, which are listed here.

# **Custom sampling**

While NumPy provides built-in distributions to sample from, we can also sample from a custom distribution with the np.random.choice function.

The code below shows example usages of np.random.choice.

In [49]:
colors = ['red', 'blue', 'green']
print(np.random.choice(colors))
print(repr(np.random.choice(colors, size=2)))
print(repr(np.random.choice(colors, size=(2, 2), p=[0.8, 0.19, 0.01])))

blue
array(['red', 'green'], dtype='<U5')
array([['red', 'red'],
       ['red', 'blue']], dtype='<U5')
