<a href="https://colab.research.google.com/github/carlosjuliogarciaorjuela/machine-learning-educative-1/blob/main/data_modeling_scikit_learn_educative_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Linear Regression
Explore the fundamentals of linear regression and how to apply it using scikit-learn. Understand fitting models to data, making predictions, and evaluating fit quality with R squared. This lesson helps you grasp when linear regression is suitable and shows how to create simple predictive models for continuous variables.

Chapter Goals:
Understand linear regression and its applications
Fit a basic linear regression model using scikit-learn
Make predictions and evaluate model performance
A. Introduction to linear regression
One of the main objectives in both machine learning and data science is finding an equation or distribution that best fits a given dataset. This is known as data modeling, where we create a model that uses the dataset’s features as independent variables to predict output values for some dependent variable (with minimal error).

However, it is incredibly difficult to find an optimal model for most datasets, given the amount of noise (i.e. random errors/fluctuations) in real world data.

Since finding an optimal model for a dataset is difficult, we instead try to find a good approximating distribution. In many cases, a linear model (a linear combination of the dataset’s features) can approximate the data well. The term linear regression refers to using a linear model to represent the relationship between a set of independent variables and a dependent variable.

y
=
a
x
1
+
b
x
2
+
c
x
3
+
d
y=ax
1
​
 +bx
2
​
 +cx
3
​
 +d

The above formula is example linear model which produces output y (dependent variable) based on the linear combination of independent variables
x
1
,
x
2
,
x
3
x
1
​
 ,x
2
​
 ,x
3
​

. The model coefficients a, b, c and intercept d determine the model’s fit.

B. Basic linear regression
The simplest form of linear regression is called least squares regression. This strategy produces a regression model, which is a linear combination of the independent variables, that minimizes the sum of squared residuals between the model’s predictions and actual values for the dependent variable.

Implementing basic linear regression with scikit-learn
In scikit-learn, the least squares regression model is implemented with the LinearRegression object, which is a part of the linear_model module in sklearn. The object contains a fit function, which takes in an input dataset of features (independent variables) and an array of labels (dependent variables) for each data observation (rows of the dataset). The code below demonstrates how to fit a LinearRegression model to a dataset of 5 different pizzas (pizza_data) and corresponding pizza prices. The first column of pizza_data represents the number of calories and the second column represents net weight (in grams).

In [4]:
# Importamos librerias
import numpy as np
from sklearn import linear_model

# Diámetro de la pizza en pulgadas (ejemplo de característica / X)
# Debe ser una matriz de 2D: cada fila es una muestra
pizza_data = np.array([[6], [8], [10], [14], [18]])

# Precio de la pizza en dólares (ejemplo de etiqueta / y)
# Puede ser un arreglo de 1D o 2D
pizza_prices = np.array([7, 9, 13, 17.5, 18])

# Verificamos los datos
print('{}\n'.format(repr(pizza_data)))
print('{}\n'.format(repr(pizza_prices)))

# Ahora ejecutas tu modelo de Scikit-Learn
reg = linear_model.LinearRegression()
reg.fit(pizza_data, pizza_prices)

print("Entrenamiento completado con éxito.")


array([[ 6],
       [ 8],
       [10],
       [14],
       [18]])

array([ 7. ,  9. , 13. , 17.5, 18. ])

Entrenamiento completado con éxito.


After calling the fit function, the model is ready to use. The predict function allows us to make predictions on new data. We can also get the specific coefficients and intercept for the linear combination using the coef_ and intercept_ properties, respectively. Finally, we can retrieve the coefficient of determination (or
R
2
R
2

 value) using the score function applied to the dataset and labels. The
R
2
R
2

 value tells us how close of a fit the linear model is to the data, or in other words, how good of a fit the model is for the data.

In [6]:
# 1. Conjunto de datos: Diámetros (pulgadas) y Precios (dólares)
pizza_data = np.array([[6], [8], [10], [14], [18]])
pizza_prices = np.array([7, 9, 13, 17.5, 18])

# 2. Creación y entrenamiento del modelo
reg = linear_model.LinearRegression()
reg.fit(pizza_data, pizza_prices)

# 3. Nuevos datos para predecir (pizzas de 12 y 16 pulgadas)
new_pizzas = np.array([[12], [16]])
price_predicts = reg.predict(new_pizzas)

# 4. Resultados de las predicciones
print('Predicciones para 12" y 16":')
print(repr(price_predicts))
print('-' * 40)

# 5. Parámetros aprendidos por la recta (y = m*x + b)
print('Pendiente (coef_): {}'.format(reg.coef_))
print('Intersección (intercept_): {:.2f}'.format(reg.intercept_))
print('-' * 40)

# 6. Evaluación de calidad del modelo (R²)
r2 = reg.score(pizza_data, pizza_prices)
print('Score R2: {:.4f}'.format(r2))

Predicciones para 12" y 16":
array([13.68103448, 17.5862069 ])
----------------------------------------
Pendiente (coef_): [0.9762931]
Intersección (intercept_): 1.97
----------------------------------------
Score R2: 0.9100


The traditional
R
2
R
2

 value is a real number between 0 and 1. In scikit-learn it ranges from -∞ to 1, where lower values denote a poorer model fit to the data. The closer the value is to 1, the better the model’s fit on the data. In the example above, we see that the model is a near-perfect fit for the pizza data.

C. When to use linear regression
Linear regression is a powerful yet simple tool for predicting continuous outcomes. It works best when the relationship between the independent variables and the dependent variable is roughly linear, and the dataset is relatively clean.

Use linear regression in the following scenarios:

Linear relationships: When features have a proportional effect on the target.

Predictive modeling: Estimating numerical outcomes such as sales, prices, or temperatures.

Baseline modeling: As a starting point before trying more complex models.

Trend analysis: Understanding how variables impact the target over time.

Low noise datasets: Works best when outliers or extreme values are minimal.

D. Advantages of linear regression
Linear regression is widely used due to its simplicity, interpretability, and efficiency. It also provides insight into the impact of each independent variable on the target, making it useful for both prediction and analysis.

Advantage

Description

Simple to implement

Easy to code and understand, even for beginners.

Interpretable

Coefficients clearly indicate the effect of each feature on the target.

Computationally efficient

Fast to train, suitable for large datasets.

Baseline model

Serves as a reference point for comparing more complex algorithms.

Supports multivariate analysis

Can handle multiple independent variables simultaneously.

Insightful

Helps understand feature-target relationships and trends in the data.